version: '1.0'

services:
 mlappdb:
  build:
   context: .
  ports:
  - 8000:5000
  volumes:
  - ./:/app
  networks:
    mysqlnet:
      ipv4_address: 172.20.0.100


 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=12345
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql\
  networks:
  - mysqlnet


volumes:
  mysql:
  mysql_config:

networks:
  mysqlnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
